package aprendizadodevdojo.devdojo.javacore.Oexception.runtime.teste;

public class RuntimeExceptionTest01 {
    public static void main(String[] args) {
        Object object = null;
        int[] nums = {1, 2};
        System.out.println(nums[2]);
    }
}
